name: Debug build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install necessary tools
      run: sudo apt install -y wget git sed coreutils libglib2.0-dev \
           libgcrypt20-dev

    - name: Build
      run: ./ushark-build.sh -t debug
