name: Debug build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install necessary tools
      run: sudo apt install -y wget git sed coreutils

    - name: Build
      run: |
        chmod +x ./ushark-build.sh
        ./ushark-build.sh -t debug
      shell: bash
