name: Debug build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install tools
      run: sudo apt install -y wget git sed coreutils

    - name: Build
      run: ./ushark-build.sh -t debug
